"""empty message

Revision ID: e3db88fefb4c
Revises: 530e66487b48
Create Date: 2023-11-19 23:13:20.645845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db88fefb4c'
down_revision = '530e66487b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cust_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('date_created', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cust_id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(), nullable=False))
        batch_op.drop_constraint('order_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['cust_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_user_id_fkey', 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('customer_id')

    op.drop_table('customer')
    # ### end Alembic commands ###
